site_name: Hapify
nav:
  - Get started: 'index.md'
  - CLI: 'cli.md'
  - Concepts:
      - Key concepts: 'concepts/key-concepts.md'
      - Models: 'concepts/models.md'
  - Templating:
      - Hapify:
        - Syntax: 'templating/hapify/syntax.md'
        - Samples: 'templating/hapify/code-samples.md'
      - JavaScript:
        - Usage: 'templating/javascript/usage.md'
        - Samples: 'templating/javascript/code-samples.md'
      - Model object: 'templating/model-object.md'
      - Models validator: 'templating/models-validator.md'
  - Best practices: 'best-practices.md'
  - Troubleshooting: 'troubleshooting.md'
theme:
  name: material
  favicon: assets/icon-192x192.png
  logo: assets/logo-no-margin-white.png
  palette:
    primary: deep purple
    accent: cyan
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.hapify.io/
    - icon: fontawesome/brands/github
      link: https://github.com/hapify
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/hapify
    - icon: fontawesome/brands/slack
      link: https://hapify.slack.com/
