site_name: Hapify
pages:
  - CLI: 'cli.md'
  - Concepts:
      - Key concepts: 'concepts/key-concepts.md'
      - Models: 'concepts/models.md'
      - Syntax: 'concepts/syntax.md'
  - Templating:
      - Samples: 'templating/code-samples.md'
      - Hapify: 'templating/templating-hapify.md'
      - JavaScript: 'templating/templating-javascript.md'
  - Best practices: 'best-practices.md'
  - Troubleshooting: 'troubleshooting.md'
theme:
  name: material
